
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app



[MaterialYou-rvx]
app-name = "og-material-you"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
options-json = "packagename.json"
apkmirror-arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'MaterialYou' 'Change version code'"
excluded-patches = "'Theme' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails' 'Visual preferences icons for YouTube'"

[Darker-MaterialYou-rvx]
app-name = "da-rker-matterialyou"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
options-json = "darker-materialyou-rvx.json"
apkmirror-arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'MaterialYou' 'Theme' 'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails' 'Visual preferences icons for YouTube'"

[Black-rvx]
app-name = "og-black"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
options-json = "packagename.json"
apkmirror-arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Theme' 'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails' 'Visual preferences icons for YouTube'"

[Dark-rvx]
app-name = "og-dark"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
options-json = "packagename.json"
apkmirror-arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change version code'"
excluded-patches = "'Theme' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails' 'Visual preferences icons for YouTube'"

[Grey-rvx]
app-name = "grey"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
options-json = "grey-rvx.json"
apkmirror-arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Theme' 'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails' 'Visual preferences icons for YouTube'"

[BlackA6-7]
app-name = "bllack"
patches-source = "kitadai31/revanced-patches-android6-7"
integrations-source = "kitadai31/revanced-integrations"
cli-source = "kitadai31/revanced-cli"
rv-brand = "rvx-a6-7"
version = "17.34.36"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'theme'"
excluded-patches = "'check-android-version' 'return-youtube-dislike' 'custom-branding-name' 'custom-branding-icon-afn-red' 'custom-branding-icon-afn-blue' 'custom-branding-icon-revancify'"

[DarkA6-7]
app-name = "darrk"
patches-source = "kitadai31/revanced-patches-android6-7"
integrations-source = "kitadai31/revanced-integrations"
cli-source = "kitadai31/revanced-cli"
rv-brand = "rvx-a6-7"
version = "17.34.36"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = ""
excluded-patches = "'check-android-version' 'return-youtube-dislike' 'theme' 'custom-branding-name' 'custom-branding-icon-afn-red' 'custom-branding-icon-afn-blue' 'custom-branding-icon-revancify'"

